### ISSUE TITLE
Motivation: Why do we need content images? And what is it?

### ISSUE THREAD

**Issue by goern** [operate-first/espresso-series#10]
**Title**
Motivation: Why do we need content images? And what is it?

**User Story**
As Data Scientist,
I want to create a content image,
so that I can share the current state of an experiment with my colleagues 

...

**Teaser**
In the next episode...

**Release Date**
TBD

**Script URL**:
TBD

/triage needs-information

**Comment by goern** [comment]
/assign @durandom 

do we want to have such a short motivational video?!

**Comment by isabelizimm** [comment]
#5 covers the motivation of having content images
