### ISSUE TITLE
Episode 7: Train a model in Elyra, the pipelines!

### ISSUE THREAD

**Issue by oindrillac** [operate-first/espresso-series#14]
**Title**
Creating Elyra Pipeline on ODH

**User Story**
As a Data Scientist, I want to create an AI Pipeline, so that data gets ingested, a model trained and the model persisted into the Git repo.

**Teaser**
what if I modify a step of the pipeline and add a new dependency?

**Comment by oindrillac** [comment]
Hello All!

Here is a [rough outline](https://docs.google.com/document/d/1gcI8QF-t9LICIuwB-Zpm2olIjYM_4ML8cFZeChw6-g0/edit?usp=sharing) of the content I am planning to share in Episode 8

@MichaelClifford @pacospace @isabelizimm @goern @durandom @Shreyanand Please review the document for the overall flow and high level content. 

Once this issue is signed off, I will start working on the final script.

**Comment by oindrillac** [comment]
The [final script](https://docs.google.com/document/d/1gcI8QF-t9LICIuwB-Zpm2olIjYM_4ML8cFZeChw6-g0/edit?usp=sharing) is ready for review. Please add your inputs!

**Comment by isabelizimm** [comment]
Hello all! Video is [here](https://drive.google.com/file/d/1GTTS7v2AoZsWctpEcHBhdwcJYrZ9MR9j/view?usp=sharing). Lmk what you think! 

CC: @MichaelClifford @aakankshaduggal @oindrillac @Shreyanand @goern @pacospace @durandom

**Comment by MichaelClifford** [comment]
:clap: 
/lgtm

**Comment by aakankshaduggal** [comment]
Looks good :+1:

**Comment by oindrillac** [comment]
thank you @isabelizimm 🥳

**Comment by isabelizimm** [comment]
Published!
https://www.youtube.com/watch?v=iMSOal8wRj4&list=PL8VBRDTElCWpneB4dBu4u1kHElZVWfAwW&index=7
