### ISSUE TITLE
Logos/Intro slides

### ISSUE THREAD

**Issue by isabelizimm** [operate-first/espresso-series#16]
**High-level Goals**
As a watcher of the Espresso Series, I want the videos to be recognizable via some sort of title slide/branding. 

**Describe the solution you'd like**
Using the Operate First logo, I would like some sort of intro (animated or not) to distinguish this series from other videos on the YouTube channel.

**Comment by MichaelClifford** [comment]
@isabelizimm any update on this issue? Is this an issue you could take on or do we need outside help? Not sure if any of us are animators : )

**Comment by isabelizimm** [comment]
Outside help would be appreciated if we want something fancy. I'm able to make some simple things and can post in this issue for review, and then we can decide if that is sufficient or if we want something more blingy :)
