### ISSUE TITLE
FINAL DRAFT: S01E05

### ISSUE THREAD

**Issue by isabelizimm** [operate-first/espresso-series#17]
**Title**

Please watch _S01E05: Tools For Data Science Collaboration_ to review before publishing.

**Release Date**
Thurs, May 27

**Script URL**: 
See #3 for script

Watch video [here](https://drive.google.com/file/d/1gx99bmB5jvZ_AXNE5mdkgpzC1JP6bgM0/view?usp=sharing) 

CC: @durandom @goern @pacospace @MichaelClifford @oindrillac @Shreyanand

**Comment by MichaelClifford** [comment]
:clap: great production work. 

The only thing I wanted to double check with the rest of the group here is that during the demo recording the dependency management tool was not working properly so we jump cut over it. Do we care about showing that bit working in this video ?

**Comment by pacospace** [comment]
>  great production work.
> 
> The only thing I wanted to double check with the rest of the group here is that during the demo recording the dependency management tool was not working properly so we jump cut over it. Do we care about showing that bit working in this video ?

I think is great like this :)

**Comment by isabelizimm** [comment]
Published [here](https://www.youtube.com/watch?v=E7J1Jrny7H4&list=PL8VBRDTElCWpneB4dBu4u1kHElZVWfAwW&index=5)
