### ISSUE TITLE
Promote Espresso Videos via Twitter

### ISSUE THREAD

**Issue by isabelizimm** [operate-first/espresso-series#22]
Organization for finishing out season 1!

Submit a tweet PR to https://github.com/operate-first/operate-first-twitter/tree/main/tweets to promote the following videos:

- [X] S01E01: Cloud Native Data Science
- [X] S01E02: Deploy Jupyter in Operate First
- [X] S01E03: Manage notebook dependencies
- [X] S01E04: Git for Data Scientists (initializing a repo)
- [X] S01E05: Git for Data Scientists (collaboration)
- [x] S01E06: Content images
- [x] S01E07: Elyra pipelines
- [x] S01E08: Troubleshooting with Grafana
- [x] S01E09: Reviewing a PR
- [ ] S01E10: Season Finale

**Comment by pacospace** [comment]
@isabelizimm I think they have all been promoted right? I think we can close this issue.

**Comment by oindrillac** [comment]
Just checked, I think 7 through 9 are not promoted yet, reopening issue
