### ISSUE TITLE
Episode 5: Content and Structure Review

### ISSUE THREAD

**Issue by MichaelClifford** [operate-first/espresso-series#3]
Here is the [rough outline](https://docs.google.com/document/d/1-WLaVr5AKcs5IrUCoZGJYd6zLlLalyZWt-gq4Q2knGs/edit) of the content I am planning to share in Episode 4. 

Please review the document for content, information and overall flow. Once this issue is signed off, I will start on the final script.

**Comment by MichaelClifford** [comment]
@durandom @goern @pacospace @isabelizimm has everyone had their chance to review? Can I move onto finalizing the script?

**Comment by isabelizimm** [comment]
The flow looks logical to me!

**Comment by durandom** [comment]
I reviewed. Looks good

**Comment by MichaelClifford** [comment]
Great! thanks all. Closing this issue since signed off by all. :+1:
