### ISSUE TITLE
Episode 6: Tag release Content Image for the the experiment

### ISSUE THREAD

**Issue by pacospace** [operate-first/espresso-series#5]
**Title**
Tag release Content Image for the the experiment

**Description**
Tag release Content Image for the the experiment, motivating the use of content images for reusable 
experiments. teaser: next video you will see what happends when a tag release is created.

**Release Date**

**Script URL**
https://docs.google.com/document/d/1HCsAz-a2xtPN90OEJS5i32gKD730darxj5tKh6VX2Lk/edit#heading=h.1vu4q9868nj4

**User Story**
As maintainer of an experiment,

I want to make sure new useful contributions are part of the experiment so everyone in the community can benefit of these changes directly on Operate First environment.

**Comment by pacospace** [comment]
Script: https://docs.google.com/document/d/1HCsAz-a2xtPN90OEJS5i32gKD730darxj5tKh6VX2Lk/edit# It describes in simple words what is the content image and why we need it, then takes Michael/Isabel changes approve them and bot/pipelines do all the rest automatically, and we show that the new tag is available in the JH list of images with new tag.

@MichaelClifford @durandom @goern @isabelizimm @oindrillac @Shreyanand feel free to start the review.

**Comment by pacospace** [comment]
> Script: https://docs.google.com/document/d/1HCsAz-a2xtPN90OEJS5i32gKD730darxj5tKh6VX2Lk/edit# It describes in simple words what is the content image and why we need it, then takes Michael/Isabel changes approve them and bot/pipelines do all the rest automatically, and we show that the new tag is available in the JH list of images with new tag.
> 
> @MichaelClifford @durandom @goern @isabelizimm @oindrillac @Shreyanand feel free to start the review.

Any feedbacks all?

**Comment by MichaelClifford** [comment]
lgtm :+1:

**Comment by Shreyanand** [comment]
lgtm :+1:

**Comment by pacospace** [comment]
Depends-On: https://github.com/AICoE/aicoe-ci/issues/115

**Comment by isabelizimm** [comment]
Hey all--

Please review video that is found [here](https://drive.google.com/file/d/1l7YQEGdg62We0HEnXIIj64gQOTLZXi15/view?usp=sharing)

@MichaelClifford @durandom @goern @oindrillac @Shreyanand @aakankshaduggal

**Comment by isabelizimm** [comment]
https://www.youtube.com/watch?v=R97BPEFgRp4 go like and subscribe!
