### ISSUE TITLE
Episode 5: Tools for Data Science Collaboration

### ISSUE THREAD

**Issue by MichaelClifford** [operate-first/espresso-series#9]
**Title**
Tools for Data Science Collaboration

**User Story**
As a Data Scientist, I want to know how to use git and jupyter lab to collaborate with team members and contribute to upstream repositories.   
...

**Teaser**
In the next video, Francesco will show you how, with  the power of Thoth, we can  propagate these changes into a shareable, reproducible and interactive content image.

**Release Date**
TBD

**Script URL**:
[Script URL](https://docs.google.com/document/d/1-WLaVr5AKcs5IrUCoZGJYd6zLlLalyZWt-gq4Q2knGs/edit)

**Comment by MichaelClifford** [comment]
@durandom @goern @pacospace @isabelizimm @oindrillac @Shreyanand 

Please review the first draft of the script [here](https://docs.google.com/document/d/1-WLaVr5AKcs5IrUCoZGJYd6zLlLalyZWt-gq4Q2knGs/edit).

Looking forward to you comments : )

**Comment by isabelizimm** [comment]
Published [here](https://www.youtube.com/watch?v=E7J1Jrny7H4&list=PL8VBRDTElCWpneB4dBu4u1kHElZVWfAwW&index=5)
